### PR TITLE
Some shield badges and some other things..

### PR DESCRIPTION
**Pull request by RaptaG**

### CODE REVIEW

**Comment by RaptaG** [comment]
I assume you prefer the non-round style

**Comment by theRookieCoder** [comment]
Yup! The rounded shadowy badges look like they're straight out of the 2010s

**Comment by RaptaG** [comment]
> Yup! The rounded shadowy badges look like they're straight out of the 2010s

Eh, was too young to remember so ok

**Comment by RaptaG** [comment]
Btw, change the Modrinth download count background color to `CCFFCC`, the current looks to bright makes it hard to read

**Pull request merged**
